#!/bin/bash
cd /tmp
echo =================================================
echo "1 - Work with pacman-mirrorlist(pacman)"
echo "2 - Latest mirrorlist(arch mirrorlist generator)"
echo "3 - Just scan and replace mirrorlist file"
echo =================================================
echo -n "Choose an action: "
read main
case "$main" in
  1) echo "Installing pacman-mirrorlist package"
  sudo pacman -S pacman-mirrorlist
  sudo reflector --verbose -l 200 -p http --sort rate --save /etc/pacman.d/mirrorlist.pacnew
  echo "Starting replace"
  cd /etc/pacman.d/
  sudo rm mirrorlist && sudo mv mirrorlist.pacnew mirrorlist
  ;;
  2) echo "Downloading fresh mirrorlist from internet"
  wget https://www.archlinux.org/mirrorlist/?country=all&protocol=http&ip_version=4
  mv index.html\?country=all mirrorlist
  sudo cp mirrorlist /etc/pacman.d/mirrorlist.pacnew
  echo Running reflector
  sudo reflector --verbose -l 200 -p http --sort rate --save /etc/pacman.d/mirrorlist.pacnew
  echo "Starting replace"
  cd /etc/pacman.d/
  sudo rm mirrorlist && sudo mv mirrorlist.pacnew mirrorlist
  ;;
  3) echo "Updating mirrorlist file"
  sudo reflector --verbose -l 200 -p http --sort rate --save /etc/pacman.d/mirrorlist.pacnew
  cd /etc/pacman.d/
  sudo rm mirrorlist && sudo mv mirrorlist.pacnew mirrorlist
  ;;
  *) echo "Error, unknown symbol.. exiting...."
  ;;
esac
echo "Running force update to test new mirrors"
sudo pacman -Syyu
echo Done!
